apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default

  source:
    repoURL: https://charts.signoz.io
    chart: signoz
    targetRevision: 0.27.0
    helm:
      values: |
        global:
          storageClass: ""

        frontend:
          service:
            type: ClusterIP

        queryService:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi

        collector:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi

        otelCollector:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi

        clickhouse:
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          persistence:
            enabled: true
            size: 10Gi

        k8s-infra:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: signoz

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
