apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storageclass
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nishant1337/cluster-bootstrap.git
    targetRevision: HEAD
    path: manifests/utilities
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
