apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default

  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: 11.3.2
  helm:
    values: |
      installCRDs: true
      upgradeCRDs: false
  
      configuration:
        backupStorageLocation:
          - name: default
            provider: filesystem
            default: true
            bucket: velero
            config:
              storageDirectory: /velero-backups
  
        excludedNamespaces:
          - kube-system
          - kube-public
          - kube-node-lease
          - argocd
          - velero
  
      snapshotsEnabled: false
      deployNodeAgent: true
  
      nodeAgent:
        podVolumePath: /var/lib/kubelet/pods
  
        extraVolumes:
          - name: velero-backups
            hostPath:
              path: /var/backups/velero
              type: DirectoryOrCreate
  
        extraVolumeMounts:
          - name: velero-backups
            mountPath: /velero-backups

  destination:
    server: https://kubernetes.default.svc
    namespace: velero

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
